### ISSUE TITLE
使用 create-umi 创建项目失败

### ISSUE THREAD

**Issue by ohhoney1** [umijs/create-umi#41]
环境：mac 10.13
```
λ cnjs [~/learn] → node -v
v10.15.1

λ cnjs [~/learn] → umi -v
2.5.5
````

操作步骤：
```
λ cnjs [~/learn] → yarn global add umi
yarn global v1.3.2
(node:46358) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
warning umi > umi-build-dev > af-webpack > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "umi > react-loadable@5.5.0" has unmet peer dependency "react@*".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@3.0.6" has unmet peer dependency "babel-eslint@9.x".
warning "umi > umi-build-dev > af-webpack > file-loader > schema-utils > ajv-errors@1.0.1" has unmet peer dependency "ajv@>=5.0.0".
[4/4] 📃  Building fresh packages...
success Installed "umi@2.5.5" with binaries:
      - umi
✨  Done in 41.69s.

λ cnjs [~/learn] → create-umi umiLearn
? Select the boilerplate type app
? Do you want to use typescript? Yes
? What functionality do you want to enable? antd, dva, code splitting, dll
events.js:174
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/templates/_gitignore
    at EditionInterface.exports.copy (/Users/cnjs/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/cnjs/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at glob.sync.filter.forEach.file (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/BasicGenerator.js:31:19)
    at Array.forEach (<anonymous>)
    at Generator.writeFiles (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/BasicGenerator.js:27:8)
    at Generator.writing (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/index.js:40:10)
    at Object.<anonymous> (/Users/cnjs/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/cnjs/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/cnjs/.config/yarn/global/node_modules/run-async/index.js:24:19
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/cnjs/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by sorrycc** [comment]
应该是 `yarn global add create-umi` 再 `create-umi umilearn`，不是 `yarn global add umi`。

**Comment by ohhoney1** [comment]
还是不行。
```
λ cnjs [~/learn] → yarn global add create-umi
yarn global v1.3.2
(node:50380) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "umi > react-loadable@5.5.0" has unmet peer dependency "react@*".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@3.0.6" has unmet peer dependency "babel-eslint@9.x".
warning "umi > umi-build-dev > af-webpack > file-loader > schema-utils > ajv-errors@1.0.1" has unmet peer dependency "ajv@>=5.0.0".
[4/4] 📃  Building fresh packages...
success Installed "create-umi@0.9.5" with binaries:
      - create-umi
✨  Done in 7.19s.

λ cnjs [~/learn] → create-umi umiLearn
? Select the boilerplate type app
? Do you want to use typescript? Yes
? What functionality do you want to enable? antd, dva, code splitting, dll
events.js:174
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/templates/_gitignore
    at EditionInterface.exports.copy (/Users/cnjs/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/cnjs/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at glob.sync.filter.forEach.file (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/BasicGenerator.js:31:19)
    at Array.forEach (<anonymous>)
    at Generator.writeFiles (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/BasicGenerator.js:27:8)
    at Generator.writing (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/index.js:40:10)
    at Object.<anonymous> (/Users/cnjs/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/cnjs/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/cnjs/.config/yarn/global/node_modules/run-async/index.js:24:19
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/cnjs/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

包都是安装正常的：
```
λ cnjs [~/learn] → yarn global list --depth=0
yarn global v1.3.2
(node:52573) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning "umi > react-loadable@5.5.0" has unmet peer dependency "react@*".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@3.0.6" has unmet peer dependency "babel-eslint@9.x".
warning "umi > umi-build-dev > af-webpack > file-loader > schema-utils > ajv-errors@1.0.1" has unmet peer dependency "ajv@>=5.0.0".
info "@vue/cli@3.0.0-rc.3" has binaries:
   - vue
info "create-umi@0.9.5" has binaries:
   - create-umi
info "parcel-bundler@1.9.7" has binaries:
   - parcel
info "umi@2.5.5" has binaries:
   - umi
✨  Done in 5.90s.

λ cnjs [~/learn] → create-umi umilearn
? Select the boilerplate type app
? Do you want to use typescript? Yes
? What functionality do you want to enable? antd, dva, code splitting, dll
events.js:174
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/templates/_gitignore
    at EditionInterface.exports.copy (/Users/cnjs/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/cnjs/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at glob.sync.filter.forEach.file (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/BasicGenerator.js:31:19)
    at Array.forEach (<anonymous>)
    at Generator.writeFiles (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/BasicGenerator.js:27:8)
    at Generator.writing (/Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/index.js:40:10)
    at Object.<anonymous> (/Users/cnjs/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/cnjs/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/cnjs/.config/yarn/global/node_modules/run-async/index.js:24:19
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/cnjs/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by sorrycc** [comment]
应该是依赖没装好，`lib/generators/app/templates/` 下是有 _gitignore 这个文件的，参考 https://unpkg.com/create-umi@0.9.5/lib/generators/app/templates/

**Comment by ohhoney1** [comment]
这个已经检查过了，是存在的。也重装过几次了，切换了几个node版本也不行，好晕。
```
λ cnjs [~] → cd /Users/cnjs/.config/yarn/global/node_modules/create-umi/lib/generators/app/templates

λ cnjs [generators/app/templates] → ls
_gitignore        package.json      tsconfig.json     typings.d.ts
mock              src               tslint.yml        webpack.config.js

λ cnjs [generators/app/templates] → tree
.
├── _gitignore
├── mock
├── package.json
├── src
│   ├── app.js
│   ├── app.ts
│   ├── assets
│   │   └── yay.jpg
│   ├── global.css
│   ├── layouts
│   │   ├── __tests__
│   │   │   ├── index.test.js
│   │   │   └── index.test.tsx
│   │   ├── index.css
│   │   ├── index.js
│   │   └── index.tsx
│   ├── models
│   └── pages
│       ├── __tests__
│       │   ├── index.test.js
│       │   └── index.test.tsx
│       ├── index.css
│       ├── index.js
│       └── index.tsx
├── tsconfig.json
├── tslint.yml
├── typings.d.ts
└── webpack.config.js

8 directories, 20 files
```

**Comment by sorrycc** [comment]
那就是权限问题，是用 sudo 或者另一个用户安装的？

**Comment by ohhoney1** [comment]
权限是没问题的。
安装 ant-design-pro block 这种模板是没问题的，只有这个 app 有问题。这个 issue 先开着吧，我有空本地继续排查下问题。
