### ISSUE TITLE
启动报错Plugin umi-plugin-react:pwa initialize failed, You need to have package.json and the name in it when using pwa.

### ISSUE THREAD

**Issue by idanyer** [umijs/create-umi#7]
C:\Users\38603\Desktop\vue\uuapp>yarn start
yarn run v1.9.4
$ umi dev
Plugin umi-plugin-react:pwa initialize failed, You need to have package.json and the name in it when using pwa.
{ AssertionError [ERR_ASSERTION]: You need to have package.json and the name in it when using pwa.
    at _default (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi-plugin-react\lib\plugins\pwa\index.js:23:23)
    at Service.initPlugin (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi-build-dev\lib\Service.js:122:7)
    at extraPlugins.forEach.plugin (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi-build-dev\lib\Service.js:145:14)
    at Array.forEach (<anonymous>)
    at Service.initPlugins (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi-build-dev\lib\Service.js:144:20)
    at Service.init (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi-build-dev\lib\Service.js:252:10)
    at Service.run (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi-build-dev\lib\Service.js:283:10)
    at Object.<anonymous> (C:\Users\38603\Desktop\vue\uuapp\node_modules\umi\lib\scripts\realDev.js:28:47)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sorrycc** [comment]
需要在 package.json 里有 `name` 属性。
